language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
addons:
  postgresql: "9.4"
install:
  - pip install git+https://github.com/bbliem/pyexiftool.git
  - pip install -r requirements.txt
before_script:
  - psql -c "CREATE DATABASE bordone_db;" -U postgres
  - psql -c "CREATE USER bordone_user WITH PASSWORD 'password12345';" -U postgres
  - psql -c "ALTER USER bordone_user CREATEDB;" -U postgres
  - cp .env.example .env
  - sudo mkdir -p /var/www/bordone-static
  - sudo mkdir -p /var/www/bordone-media
  - sudo chown travis:travis /var/www/bordone-static
  - sudo chown travis:travis /var/www/bordone-media
  - python manage.py migrate
  - python manage.py collectstatic
script:
  - python manage.py test
