# Generated by Django 2.1.3 on 2018-11-17 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('num_views', models.IntegerField(default=0, verbose_name='number of views')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('num_views', models.IntegerField(default=0, verbose_name='number of views')),
                ('original', models.ImageField(upload_to='')),
                ('date_taken', models.DateTimeField()),
                ('make', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('lens', models.CharField(max_length=200)),
                ('aperture', models.DecimalField(decimal_places=2, max_digits=4)),
                ('focal_length', models.DecimalField(decimal_places=2, max_digits=6)),
                ('shut_numer', models.IntegerField(verbose_name='shutter speed numerator')),
                ('shut_denom', models.IntegerField(verbose_name='shutter speed denominator')),
                ('iso', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='cover_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gallery.Photo'),
        ),
        migrations.AddField(
            model_name='album',
            name='photos',
            field=models.ManyToManyField(to='gallery.Photo'),
        ),
    ]
