# Generated by Django 2.1.6 on 2019-02-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20190206_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='photos',
            field=models.ManyToManyField(blank=True, to='gallery.Photo'),
        ),
    ]
