# Generated by Django 2.1.4 on 2018-12-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20181214_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='shut_denom',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='shut_numer',
        ),
        migrations.AddField(
            model_name='photo',
            name='shutter_speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
