# Generated by Django 2.1.4 on 2018-12-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20181215_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='aperture',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='focal_length',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
