# Generated by Django 2.1.4 on 2018-12-16 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20181215_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='original',
            field=models.ImageField(upload_to='%Y/%m/%d'),
        ),
    ]
