# Generated by Django 2.1.4 on 2018-12-16 15:17

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20181216_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='original',
            field=models.ImageField(upload_to=gallery.models.original_path),
        ),
    ]
