# Generated by Django 2.1.4 on 2018-12-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20181216_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='lens',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='photo',
            name='make',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='photo',
            name='model',
            field=models.CharField(default='', max_length=200),
        ),
    ]
