# Generated by Django 2.1.5 on 2019-01-18 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_auto_20190118_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='num_views',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='num_views',
        ),
    ]
