# Generated by Django 2.1.5 on 2019-01-31 13:32
# BB: Changed according to
# https://stackoverflow.com/questions/37309782/django-generate-slug-field-data-for-existing-entries-in-database

import autoslug.fields
from django.db import migrations

from gallery.models import Album, Photo

def migrate_data_forward(apps, schema_editor):
    for instance in Photo.objects.all():
        print(f"Generating slug for photo {instance}")
        instance.save() # Will trigger slug update

    for instance in Album.objects.all():
        print(f"Generating slug for album {instance}")
        instance.save() # Will trigger slug update

def migrate_data_backward(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_photo_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='title', unique=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='name', unique=True, null=True),
            preserve_default=False,
        ),
        migrations.RunPython(
            migrate_data_forward,
            migrate_data_backward,
        ),
    ]
